# Generated by Django 2.1 on 2018-09-18 01:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('added_date', models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 17, 20, 32, 17, 76953))),
                ('application_name', models.CharField(max_length=250)),
                ('description', models.TextField()),
            ],
        ),
    ]
