# Generated by Django 2.1 on 2018-10-01 01:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_name', models.CharField(max_length=250)),
                ('log_type', models.CharField(max_length=200)),
                ('added_date', models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 30, 20, 7, 8, 949988))),
                ('log_description', models.TextField()),
            ],
        ),
    ]
