# Generated by Django 2.1 on 2019-02-03 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='added_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 3, 14, 2, 24, 511659)),
        ),
    ]
