# Generated by Django 2.1 on 2018-08-25 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lms',
            new_name='Log',
        ),
    ]
